import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, FileSearch, Play, Download, Moon, Clock, CheckCircle2 } from 'lucide-react';
import './styles.css';

type Result = { summary: Record<string, number>; report: string; timeline: Array<{ timestamp:string; source_file:string; severity:string; message:string }>; repeated_errors:Array<{message:string;count:number}> };
const API = 'http://localhost:8000';

function App() {
  const [folder, setFolder] = useState(''); const [target, setTarget] = useState('23.01.26 13:16:11');
  const [windowSeconds, setWindowSeconds] = useState(5); const [issue, setIssue] = useState('');
  const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function investigate() { setLoading(true); setError(''); try { const res = await fetch(`${API}/api/investigations`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder_path:folder,target_timestamp:target,window_seconds:windowSeconds,user_context:{issue_description:issue}})}); const data=await res.json(); if(!res.ok) throw new Error(data.detail || 'Investigation failed'); setResult(data); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to reach backend'); } finally { setLoading(false); } }
  async function exportReport(format:string) { if (!result) return; const res=await fetch(`${API}/api/export/${format}`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(result)}); const blob=await res.blob(); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`incident-report.${format}`; a.click(); URL.revokeObjectURL(a.href); }
  return <main><header><div className="brand"><span className="logo"><FileSearch size={21}/></span><div><h1>Incident Investigator</h1><p>AI-assisted log correlation</p></div></div><button className="icon"><Moon size={18}/></button></header>
  <section className="hero"><div><span className="eyebrow">INVESTIGATION WORKSPACE</span><h2>Turn dispersed logs into a clear incident narrative.</h2><p>Stream and correlate timestamped events across your log directory, then export a shareable investigation report.</p></div><div className="health"><CheckCircle2/> Service ready<br/><small>FastAPI local analysis engine</small></div></section>
  <div className="grid"><section className="card setup"><h3>1. Configure investigation</h3><label>Log folder path<input value={folder} onChange={e=>setFolder(e.target.value)} placeholder="D:\\logs\\production" /></label><div className="twocol"><label>Target timestamp<input value={target} onChange={e=>setTarget(e.target.value)} /></label><label>Window (seconds)<input type="number" min="0" value={windowSeconds} onChange={e=>setWindowSeconds(+e.target.value)} /></label></div><label>Issue description <span>optional</span><textarea value={issue} onChange={e=>setIssue(e.target.value)} placeholder="What was the customer or service impact?" /></label><button className="primary" onClick={investigate} disabled={!folder || loading}><Play size={17}/>{loading ? 'Analysing logs…' : 'Start investigation'}</button>{error && <p className="error"><AlertTriangle size={16}/>{error}</p>}</section>
  <section className="card context"><h3>What the engine does</h3><ol><li><span>01</span>Recursively discovers supported logs</li><li><span>02</span>Normalizes six common timestamp formats</li><li><span>03</span>Joins multiline Java-style stack traces</li><li><span>04</span>Correlates events in the selected window</li></ol><p className="note"><Clock size={16}/> Large files are read line-by-line to limit memory use.</p></section></div>
  {result && <><section className="metrics">{[['Files scanned','files_scanned'],['Events parsed','events_parsed'],['Window matches','matching_events'],['Errors','errors']].map(([name,key])=><div className="metric" key={key}><p>{name}</p><strong>{result.summary[key]}</strong></div>)}</section>
  <div className="results"><section className="card report"><div className="section-title"><div><span className="eyebrow">AI INVESTIGATION</span><h3>Investigation report</h3></div><div className="exports">{['pdf','md','html','txt'].map(f=><button key={f} onClick={()=>exportReport(f)}><Download size={14}/>{f.toUpperCase()}</button>)}</div></div><article>{result.report}</article></section><section className="card events"><h3>Correlated timeline</h3>{result.timeline.length ? result.timeline.slice(0,100).map((event,i)=><div className="event" key={i}><time>{new Date(event.timestamp).toLocaleTimeString()}</time><span className={'badge '+event.severity.toLowerCase()}>{event.severity}</span><p>{event.message}</p><small>{event.source_file}</small></div>) : <p className="empty">No events fell within this time window.</p>}</section></div></>}
  </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
